# Plik konfiguracyjny poziomów gry Memory
# Format: NAZWA_POZIOMU|ROZMIAR_PLANSZY|EMOJI1,EMOJI2,...
# Rozmiar planszy musi być parzystą liczbą (2, 4, 6...)
# Liczba emoji musi wynosić (ROZMIAR * ROZMIAR) / 2 unikalnych znaków

Łatwy 2x2|2|😈,👽
Średni 4x4|4|🐶,🐱,🐭,🐹,🦊,🐻,🐼,🐨
Trudny 6x6|6|🍎,🍊,🍋,🍇,🍓,🍒,🥭,🍍,🥝,🍑,🍈,🫐,🥥,🍌,🍉,🍏,🍐,🍑
